CREATE DATABASE SistemaDeProntuariosInexistentes;

USE SistemaDeProntuariosInexistentes;

CREATE TABLE user (
    id_user INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(20) NOT NULL,
    type ENUM('DOCTOR', 'PATIENT')
);

CREATE TABLE doctor (
    crm VARCHAR(10) PRIMARY KEY,
    id_user INT UNSIGNED,
    specialty ENUM('ANESTESIOLOGIA', 'CARDIOLOGIA', 'DERMATOLOGIA', 'ENDOCRINOLOGIA', 'GASTROENTEROLOGIA', 'GERIATRIA', 'GINECOLOGIA_E_OBSTETRICIA', 'HEMATOLOGIA', 'INFECTOLOGIA', 'MASTOLOGIA', 'MEDICINA_DO_TRABALHO', 'NEFROLOGIA', 'NEUROLOGIA', 'OFTALMOLOGIA', 'ONCOLOGIA', 'ORTOPEDIA_E_TRAUMATOLOGIA', 'OTORRINOLARINGOLOGIA', 'PEDIATRIA', 'PNEUMOLOGIA', 'PSICOLOGIA', 'PSIQUIATRIA', 'RADIOLOGIA', 'REUMATOLOGIA', 'UROLOGIA'),
    CONSTRAINT FK_doctor_id_user FOREIGN KEY (id_user) REFERENCES user(id_user)
);

CREATE TABLE patient (
    cpf VARCHAR(14) PRIMARY KEY,
    id_user INT UNSIGNED,
    CONSTRAINT FK_patient_id_user FOREIGN KEY (id_user) REFERENCES user(id_user)
);

CREATE TABLE appointment (
    id_appointment INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    crm VARCHAR(10) NOT NULL,
    date DATE,
    time TIME,
    CONSTRAINT FK_appointment_crm FOREIGN KEY (crm) REFERENCES doctor(crm)
);

DROP DATABASE SistemaDeProntuariosInexistentes;